-- ============================================================================
-- 001_inicial.sql — Schema PostgreSQL multi-tenant do Falatta (FIL-58).
--
-- Traduz TODAS as tabelas da DDL Oracle de referência
-- (docs/referencia/schema-oracle/ — estado final consolidado das fases) e
-- adiciona a fundação multi-tenant: tabela `tenant`, coluna `tenant_id` em
-- todas as tabelas e Row-Level Security por tabela.
--
-- COMO APLICAR (Neon — use a connection string DIRETA para DDL, se tiver):
--   psql "$DATABASE_URL" -f server/db/migrations/001_inicial.sql
--
-- IDEMPOTENTE: pode rodar mais de uma vez (IF NOT EXISTS / DROP POLICY IF
-- EXISTS + CREATE). Nunca edite este arquivo depois de aplicado em um
-- ambiente compartilhado — mudança de schema é migração NOVA e numerada.
--
-- DE→PARA de nomes (o prefixo MC_ZAP_ era resíduo do fork; ver README
-- "Ainda com resíduo" e docs/PORTE.md §1.4):
--   MC_ZAP_NUMERO→numero · MC_ZAP_ATENDENTE→atendente · MC_ZAP_TEMPLATE→
--   template · MC_ZAP_CONTATO→contato · MC_ZAP_TAG→tag · MC_ZAP_CONVERSA→
--   conversa · MC_ZAP_MENSAGEM→mensagem · MC_ZAP_RESPOSTA_RAPIDA→
--   resposta_rapida · MC_ZAP_CAMPANHA→campanha · MC_ZAP_CAMPANHA_ITEM→
--   campanha_item · MC_ZAP_AUDITORIA→auditoria · MC_ZAP_EVENTO_WEBHOOK→
--   evento_webhook · MC_ZAP_DEPARTAMENTO→departamento · MC_ZAP_ATENDENTE_DEPTO
--   →atendente_depto · MC_ZAP_ATENDENTE_NUMERO→atendente_numero · MC_ZAP_FLUXO
--   →fluxo · MC_ZAP_CONFIG→config · MC_ZAP_IA_CONFIG→ia_config ·
--   MC_ZAP_IA_TURNO→ia_turno · MC_ZAP_IA_AUTORIZADO→ia_autorizado ·
--   MC_ZAP_SEQ_PROTOCOLO→seq_protocolo
--
-- Equivalências de tipo aplicadas (ticket FIL-58):
--   GENERATED BY DEFAULT AS IDENTITY → GENERATED ALWAYS AS IDENTITY
--   SYSTIMESTAMP → now() · CLOB de JSON / "IS JSON" → jsonb · CLOB → text
--   NUMBER → bigint (ids/contagens) ou numeric(p,s) (valores)
--   VARCHAR2(n) → varchar(n) · TIMESTAMP → timestamptz
--
-- MULTI-TENANCY (modelo: shared schema + RLS — docs/PORTE.md §1.2):
--   • `tenant_id` NOT NULL em toda tabela, com DEFAULT tenant_atual() — um
--     INSERT dentro de comTenant() não precisa citar a coluna.
--   • RLS ENABLE + FORCE em toda tabela (FORCE: até o OWNER da tabela passa
--     pela policy — no Neon o app conecta como owner).
--   • Policy única `isolamento_tenant` por tabela: USING + WITH CHECK
--     `tenant_id = tenant_atual()`. Sem contexto de tenant ⇒ zero linhas.
--   • O contexto vem de set_config('app.current_tenant_id', $1, true) — o
--     `true` (transaction-scoped) é OBRIGATÓRIO. NUNCA SET SESSION: o pooler
--     do Neon (PgBouncer transaction mode) reusa a conexão entre requisições.
--   • FKs internas são compostas (tenant_id, id) — impede uma linha do
--     tenant A apontar para um pai do tenant B mesmo com id "chutado".
--   • Tabela `tenant`: policy `tenant_proprio` (enxerga a própria linha) +
--     `tenant_operador` (contexto NULO = operador/provisionamento enxerga
--     tudo — só nela; nas tabelas de dados, contexto nulo = nada).
--   • ⚠️ Role de aplicação `falatta_app` (NOLOGIN, NOBYPASSRLS): o dono do
--     banco no Neon (`neondb_owner`) tem rolbypassrls = true e IGNORA a RLS
--     mesmo com FORCE — verificado no banco de dev: o tenant B lia a linha do
--     tenant A. Por isso `comTenant()` executa `SET LOCAL ROLE falatta_app`
--     antes do set_config: dentro da transação o papel efetivo passa a ser um
--     role sem bypass, e as policies valem. É transaction-scoped como o
--     set_config — compatível com o pooler. Sem este role a RLS é decorativa.
--
-- Seeds da DDL Oracle (departamentos, config despedida/fora-de-horário) NÃO
-- entram aqui: eram dados do cliente original ou são por tenant — nascem no
-- provisionamento do tenant (fora deste ticket).
-- ============================================================================

-- Contexto de tenant corrente (NULL se não setado — ver cabeçalho).
CREATE OR REPLACE FUNCTION tenant_atual() RETURNS bigint
  LANGUAGE sql STABLE
  AS $$ SELECT NULLIF(current_setting('app.current_tenant_id', true), '')::bigint $$;

-- ----------------------------------------------------------------------------
-- tenant — a empresa cliente do SaaS.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tenant (
  id        bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nome      varchar(160) NOT NULL,
  slug      varchar(60)  NOT NULL,
  status    varchar(20)  NOT NULL DEFAULT 'ativo',
  criado_em timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT uq_tenant_slug  UNIQUE (slug),
  CONSTRAINT ck_tenant_status CHECK (status IN ('ativo','suspenso','encerrado'))
);

-- Protocolo de atendimento (YYMMDD + 6 dígitos). Global: único entre tenants.
CREATE SEQUENCE IF NOT EXISTS seq_protocolo START WITH 100000;

-- ----------------------------------------------------------------------------
-- departamento — equipes/filas de atendimento.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS departamento (
  id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  tenant_id  bigint NOT NULL DEFAULT tenant_atual() REFERENCES tenant (id),
  nome       varchar(80) NOT NULL,
  descricao  varchar(200),
  cor        varchar(9),
  ativo      char(1) NOT NULL DEFAULT 'S',
  criado_em  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_depto_tenant_id   UNIQUE (tenant_id, id),
  CONSTRAINT uq_depto_nome        UNIQUE (tenant_id, nome),
  CONSTRAINT ck_depto_ativo       CHECK (ativo IN ('S','N'))
);

-- ----------------------------------------------------------------------------
-- atendente — usuários do painel (RBAC). MATRICULA era o vínculo com o ERP do
-- cliente original; permanece como identificador de login até o FIL-59.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS atendente (
  id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  tenant_id       bigint NOT NULL DEFAULT tenant_atual() REFERENCES tenant (id),
  matricula       bigint NOT NULL,
  nome            varchar(120),
  papel           varchar(20) NOT NULL DEFAULT 'ATENDENTE',
  codfilial       bigint,
  ativo           char(1) NOT NULL DEFAULT 'S',
  status_presenca varchar(10) NOT NULL DEFAULT 'offline',
  pode_ativo      char(1) NOT NULL DEFAULT 'N',
  criado_em       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_atd_tenant_id UNIQUE (tenant_id, id),
  CONSTRAINT uq_atd_matricula UNIQUE (tenant_id, matricula),
  CONSTRAINT ck_atd_papel     CHECK (papel IN ('ADMIN','SUPERVISOR','ATENDENTE','AUDITOR')),
  CONSTRAINT ck_atd_ativo     CHECK (ativo IN ('S','N')),
  CONSTRAINT ck_atd_presenca  CHECK (status_presenca IN ('online','pausa','offline')),
  CONSTRAINT ck_atd_podeativo CHECK (pode_ativo IN ('S','N'))
);

-- ----------------------------------------------------------------------------
-- numero — números de WhatsApp do tenant (multi-número por webhook).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS numero (
  id                     bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  tenant_id              bigint NOT NULL DEFAULT tenant_atual() REFERENCES tenant (id),
  phone_number_id        varchar(40) NOT NULL,
  display_phone          varchar(30),
  waba_id                varchar(40),
  nome_exibicao          varchar(120),
  departamento           varchar(60),
  codfilial              bigint,
  quality_rating         varchar(10),
  messaging_tier         varchar(20),
  limite_diario          integer NOT NULL DEFAULT 250,
  permite_ativo          char(1) NOT NULL DEFAULT 'S',
  ativo                  char(1) NOT NULL DEFAULT 'S',
  modo                   varchar(10) NOT NULL DEFAULT 'padrao',
  departamento_padrao_id bigint,
  criado_em              timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_num_tenant_id UNIQUE (tenant_id, id),
  -- GLOBAL, não por tenant: o webhook da Meta identifica o tenant A PARTIR do
  -- phone_number_id. Se dois tenants registrassem o mesmo número, a mensagem
  -- de um cliente poderia cair no tenant errado. É a única unicidade do schema
  -- que NÃO é escopada por tenant — e por isso a tentativa de registrar um
  -- número já usado precisa ser tratada como conflito na camada de aplicação.
  CONSTRAINT uq_num_pnid      UNIQUE (phone_number_id),
  CONSTRAINT ck_num_ativo     CHECK (ativo IN ('S','N')),
  CONSTRAINT ck_num_permativo CHECK (permite_ativo IN ('S','N')),
  CONSTRAINT ck_num_modo      CHECK (modo IN ('padrao','ia')),
  CONSTRAINT fk_num_deppad    FOREIGN KEY (tenant_id, departamento_padrao_id)
    REFERENCES departamento (tenant_id, id)
);
-- A unicidade acima é global; este índice serve as listagens por tenant
-- (padrão do schema: tenant_id como primeira coluna).
CREATE INDEX IF NOT EXISTS ix_num_pnid ON numero (tenant_id, phone_number_id);

-- ----------------------------------------------------------------------------
-- template — HSMs gerenciados pela plataforma e submetidos à Meta.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS template (
  id            bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  tenant_id     bigint NOT NULL DEFAULT tenant_atual() REFERENCES tenant (id),
  nome          varchar(100) NOT NULL,
  idioma        varchar(10)  NOT NULL DEFAULT 'pt_BR',
  categoria     varchar(20),
  status_meta   varchar(20) DEFAULT 'PENDENTE',
  corpo         text,
  variaveis     jsonb,
  botoes        jsonb,
  waba_id       varchar(40),
  criado_por    bigint,
  criado_em     timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz,
  CONSTRAINT uq_tpl_tenant_id UNIQUE (tenant_id, id),
  CONSTRAINT uq_tpl           UNIQUE (tenant_id, nome, idioma),
  CONSTRAINT fk_tpl_atd       FOREIGN KEY (tenant_id, criado_por)
    REFERENCES atendente (tenant_id, id)
);

-- ----------------------------------------------------------------------------
-- contato — dedup por telefone E.164 sem '+'. Estado atual de opt-in aqui;
-- trilha na auditoria. CODCLI/CGCENT são resíduo do fork (generalização é
-- outro ticket — ver PORTE.md "Resíduo conhecido").
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS contato (
  id             bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  tenant_id      bigint NOT NULL DEFAULT tenant_atual() REFERENCES tenant (id),
  telefone       varchar(20) NOT NULL,
  wa_id          varchar(30),
  nome_perfil    varchar(200),
  codcli         bigint,
  cgcent         varchar(20),
  optin          char(1) NOT NULL DEFAULT 'N',
  optin_origem   varchar(60),
  optin_em       timestamptz,
  nome_interno   varchar(200),
  observacoes    varchar(2000),
  tags_contato   jsonb,
  atualizado_por bigint,
  atualizado_em  timestamptz,
  criado_em      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_contato_tenant_id UNIQUE (tenant_id, id),
  CONSTRAINT uq_contato_tel       UNIQUE (tenant_id, telefone),
  CONSTRAINT ck_contato_optin     CHECK (optin IN ('S','N')),
  CONSTRAINT fk_contato_atd       FOREIGN KEY (tenant_id, atualizado_por)
    REFERENCES atendente (tenant_id, id)
);
-- Em instalações já migradas, 002 renomeou CODCLI/CGCENT. Um rerun da 001
-- precisa escolher o nome de coluna que existe hoje, sem falhar no parse.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
     WHERE table_schema = 'public' AND table_name = 'contato' AND column_name = 'codcli'
  ) THEN
    EXECUTE 'CREATE INDEX IF NOT EXISTS ix_contato_codcli ON contato (tenant_id, codcli)';
  ELSE
    EXECUTE 'CREATE INDEX IF NOT EXISTS ix_contato_codigo_externo ON contato (tenant_id, codigo_externo)';
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
     WHERE table_schema = 'public' AND table_name = 'contato' AND column_name = 'cgcent'
  ) THEN
    EXECUTE 'CREATE INDEX IF NOT EXISTS ix_contato_cgcent ON contato (tenant_id, cgcent)';
  ELSE
    EXECUTE 'CREATE INDEX IF NOT EXISTS ix_contato_documento ON contato (tenant_id, documento)';
  END IF;
END
$$;

-- ----------------------------------------------------------------------------
-- tag — catálogo de etiquetas (a atribuição fica em conversa.tags / jsonb).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tag (
  id        bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL DEFAULT tenant_atual() REFERENCES tenant (id),
  nome      varchar(60) NOT NULL,
  cor       varchar(9),
  CONSTRAINT uq_tag_tenant_id UNIQUE (tenant_id, id),
  CONSTRAINT uq_tag_nome      UNIQUE (tenant_id, nome)
);

-- ----------------------------------------------------------------------------
-- fluxo — definição do chatbot de fluxos (JSON de nós). Um ativo por número.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fluxo (
  id            bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  tenant_id     bigint NOT NULL DEFAULT tenant_atual() REFERENCES tenant (id),
  nome          varchar(120) NOT NULL,
  numero_id     bigint,
  definicao     jsonb NOT NULL,
  ativo         char(1) NOT NULL DEFAULT 'N',
  versao        integer NOT NULL DEFAULT 1,
  criado_por    bigint,
  criado_em     timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz,
  CONSTRAINT uq_fluxo_tenant_id UNIQUE (tenant_id, id),
  CONSTRAINT ck_fluxo_ativo     CHECK (ativo IN ('S','N')),
  CONSTRAINT fk_fluxo_num       FOREIGN KEY (tenant_id, numero_id)
    REFERENCES numero (tenant_id, id),
  CONSTRAINT fk_fluxo_atd       FOREIGN KEY (tenant_id, criado_por)
    REFERENCES atendente (tenant_id, id)
);
CREATE INDEX IF NOT EXISTS ix_fluxo_num ON fluxo (tenant_id, numero_id, ativo);

-- ----------------------------------------------------------------------------
-- conversa — uma por contato/número; janela de 24h; ciclo de fila; estado do
-- bot (1:1, vida curta); origem ativa/receptiva; aviso de fora de horário.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS conversa (
  id                   bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  tenant_id            bigint NOT NULL DEFAULT tenant_atual() REFERENCES tenant (id),
  contato_id           bigint NOT NULL,
  numero_id            bigint,
  atendente_id         bigint,
  status               varchar(20) NOT NULL DEFAULT 'aberta',
  tags                 jsonb,
  janela_expira_em     timestamptz,
  ultima_msg_em        timestamptz,
  departamento_id      bigint,
  fila_status          varchar(20) NOT NULL DEFAULT 'em_atendimento',
  protocolo            varchar(14),
  fila_entrou_em       timestamptz,
  atribuida_em         timestamptz,
  primeira_resposta_em timestamptz,
  resolvida_em         timestamptz,
  bot_fluxo_id         bigint,
  bot_no_atual         varchar(40),
  bot_variaveis        jsonb,
  bot_invalidas        integer DEFAULT 0,
  bot_ultima_interacao timestamptz,
  origem               varchar(12) NOT NULL DEFAULT 'receptiva',
  aviso_fora_horario   char(1) NOT NULL DEFAULT 'N',
  criado_em            timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_conv_tenant_id UNIQUE (tenant_id, id),
  CONSTRAINT uq_conv_prot      UNIQUE (tenant_id, protocolo),
  CONSTRAINT ck_conv_fila      CHECK (fila_status IN ('bot','aguardando','em_atendimento','resolvida','ia')),
  CONSTRAINT ck_conv_origem    CHECK (origem IN ('receptiva','ativa')),
  CONSTRAINT ck_conv_avisofh   CHECK (aviso_fora_horario IN ('S','N')),
  CONSTRAINT fk_conv_contato   FOREIGN KEY (tenant_id, contato_id)      REFERENCES contato (tenant_id, id),
  CONSTRAINT fk_conv_numero    FOREIGN KEY (tenant_id, numero_id)       REFERENCES numero (tenant_id, id),
  CONSTRAINT fk_conv_atd       FOREIGN KEY (tenant_id, atendente_id)    REFERENCES atendente (tenant_id, id),
  CONSTRAINT fk_conv_depto     FOREIGN KEY (tenant_id, departamento_id) REFERENCES departamento (tenant_id, id),
  CONSTRAINT fk_conv_fluxo     FOREIGN KEY (tenant_id, bot_fluxo_id)    REFERENCES fluxo (tenant_id, id)
);
CREATE INDEX IF NOT EXISTS ix_conv_contato ON conversa (tenant_id, contato_id);
CREATE INDEX IF NOT EXISTS ix_conv_status  ON conversa (tenant_id, status);
CREATE INDEX IF NOT EXISTS ix_conv_atd     ON conversa (tenant_id, atendente_id);
CREATE INDEX IF NOT EXISTS ix_conv_fila    ON conversa (tenant_id, fila_status, departamento_id);

-- ----------------------------------------------------------------------------
-- mensagem — in/out/nota; histórico permanente; mídia embutida; dedup WAMID.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mensagem (
  id            bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  tenant_id     bigint NOT NULL DEFAULT tenant_atual() REFERENCES tenant (id),
  conversa_id   bigint,
  contato_id    bigint,
  numero_id     bigint,
  atendente_id  bigint,
  template_id   bigint,
  wamid         varchar(128),
  direcao       varchar(4) NOT NULL,
  tipo          varchar(30),
  conteudo      text,
  status        varchar(20),
  erro_codigo   varchar(20),
  ts            timestamptz,
  media_id      varchar(128),
  mime_type     varchar(120),
  nome_arquivo  varchar(260),
  midia_caminho varchar(500),
  midia_tamanho bigint,
  midia_sha256  varchar(64),
  criado_em     timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_msg_tenant_id UNIQUE (tenant_id, id),
  CONSTRAINT uq_msg_wamid     UNIQUE (tenant_id, wamid),
  CONSTRAINT ck_msg_dir       CHECK (direcao IN ('in','out','nota')),
  CONSTRAINT fk_msg_conv      FOREIGN KEY (tenant_id, conversa_id)  REFERENCES conversa (tenant_id, id),
  CONSTRAINT fk_msg_contato   FOREIGN KEY (tenant_id, contato_id)   REFERENCES contato (tenant_id, id),
  CONSTRAINT fk_msg_numero    FOREIGN KEY (tenant_id, numero_id)    REFERENCES numero (tenant_id, id),
  CONSTRAINT fk_msg_atd       FOREIGN KEY (tenant_id, atendente_id) REFERENCES atendente (tenant_id, id),
  CONSTRAINT fk_msg_tpl       FOREIGN KEY (tenant_id, template_id)  REFERENCES template (tenant_id, id)
);
CREATE INDEX IF NOT EXISTS ix_msg_status ON mensagem (tenant_id, status);
CREATE INDEX IF NOT EXISTS ix_msg_conv   ON mensagem (tenant_id, conversa_id);
CREATE INDEX IF NOT EXISTS ix_msg_ts     ON mensagem (tenant_id, ts);

-- ----------------------------------------------------------------------------
-- resposta_rapida — atalhos "/" do composer (escopo pessoal ou departamento).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS resposta_rapida (
  id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  tenant_id       bigint NOT NULL DEFAULT tenant_atual() REFERENCES tenant (id),
  atalho          varchar(40),
  titulo          varchar(120),
  conteudo        text,
  escopo          varchar(15) NOT NULL DEFAULT 'pessoal',
  departamento_id bigint,
  criado_por      bigint,
  criado_em       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_rr_tenant_id UNIQUE (tenant_id, id),
  CONSTRAINT ck_rr_escopo    CHECK (escopo IN ('pessoal','departamento')),
  CONSTRAINT fk_rr_atd       FOREIGN KEY (tenant_id, criado_por)      REFERENCES atendente (tenant_id, id),
  CONSTRAINT fk_rr_depto     FOREIGN KEY (tenant_id, departamento_id) REFERENCES departamento (tenant_id, id)
);

-- ----------------------------------------------------------------------------
-- campanha / campanha_item — disparo ativo em lote com throttle e janela.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS campanha (
  id            bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  tenant_id     bigint NOT NULL DEFAULT tenant_atual() REFERENCES tenant (id),
  nome          varchar(160) NOT NULL,
  numero_id     bigint,
  template_id   bigint,
  template_nome varchar(120),
  lang          varchar(10) DEFAULT 'pt_BR',
  segmento      jsonb,
  agendamento   timestamptz,
  status        varchar(20) NOT NULL DEFAULT 'rascunho',
  total         integer NOT NULL DEFAULT 0,
  enviados      integer NOT NULL DEFAULT 0,
  rate_por_seg  integer NOT NULL DEFAULT 10,
  janela_inicio varchar(5) NOT NULL DEFAULT '08:00',
  janela_fim    varchar(5) NOT NULL DEFAULT '20:00',
  pausa_motivo  varchar(200),
  retoma_em     timestamptz,
  criado_por    bigint,
  criado_em     timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz,
  CONSTRAINT uq_camp_tenant_id UNIQUE (tenant_id, id),
  CONSTRAINT fk_camp_num       FOREIGN KEY (tenant_id, numero_id)   REFERENCES numero (tenant_id, id),
  CONSTRAINT fk_camp_tpl       FOREIGN KEY (tenant_id, template_id) REFERENCES template (tenant_id, id),
  CONSTRAINT fk_camp_atd       FOREIGN KEY (tenant_id, criado_por)  REFERENCES atendente (tenant_id, id)
);
CREATE INDEX IF NOT EXISTS ix_camp_status ON campanha (tenant_id, status);

CREATE TABLE IF NOT EXISTS campanha_item (
  id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  tenant_id   bigint NOT NULL DEFAULT tenant_atual() REFERENCES tenant (id),
  campanha_id bigint NOT NULL,
  contato_id  bigint,
  telefone    varchar(20),
  variaveis   jsonb,
  wamid       varchar(128),
  status      varchar(20) DEFAULT 'pendente',
  erro_codigo varchar(20),
  custo       numeric(10,4),
  tentativas  integer NOT NULL DEFAULT 0,
  enviado_em  timestamptz,
  CONSTRAINT uq_ci_tenant_id UNIQUE (tenant_id, id),
  CONSTRAINT uq_ci_camp_tel  UNIQUE (tenant_id, campanha_id, telefone),
  CONSTRAINT fk_ci_camp      FOREIGN KEY (tenant_id, campanha_id) REFERENCES campanha (tenant_id, id),
  CONSTRAINT fk_ci_contato   FOREIGN KEY (tenant_id, contato_id)  REFERENCES contato (tenant_id, id)
);
CREATE INDEX IF NOT EXISTS ix_ci_camp     ON campanha_item (tenant_id, campanha_id);
CREATE INDEX IF NOT EXISTS ix_ci_status   ON campanha_item (tenant_id, status);
CREATE INDEX IF NOT EXISTS ix_ci_wamid    ON campanha_item (tenant_id, wamid);
CREATE INDEX IF NOT EXISTS ix_ci_dispatch ON campanha_item (tenant_id, campanha_id, status);

-- ----------------------------------------------------------------------------
-- auditoria — trilha genérica (inclui histórico de opt-in/out — LGPD).
-- Sem FKs de propósito (a DDL original também não tinha): a trilha não pode
-- falhar por integridade referencial.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS auditoria (
  id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  tenant_id    bigint NOT NULL DEFAULT tenant_atual() REFERENCES tenant (id),
  atendente_id bigint,
  matricula    bigint,
  acao         varchar(60),
  entidade     varchar(40),
  entidade_id  bigint,
  detalhe      jsonb,
  ip           varchar(45),
  criado_em    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_aud_tenant_id UNIQUE (tenant_id, id)
);
CREATE INDEX IF NOT EXISTS ix_aud_ent  ON auditoria (tenant_id, entidade, entidade_id);
CREATE INDEX IF NOT EXISTS ix_aud_acao ON auditoria (tenant_id, acao);
CREATE INDEX IF NOT EXISTS ix_aud_dt   ON auditoria (tenant_id, criado_em);

-- ----------------------------------------------------------------------------
-- evento_webhook — log bruto de eventos (append-only, auditoria/replay).
-- payload fica text (corpo bruto usado na validação de assinatura).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS evento_webhook (
  id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  tenant_id       bigint NOT NULL DEFAULT tenant_atual() REFERENCES tenant (id),
  phone_number_id varchar(40),
  payload         text NOT NULL,
  assinatura_ok   char(1) NOT NULL DEFAULT 'N',
  processado      char(1) NOT NULL DEFAULT 'N',
  erro            varchar(4000),
  recebido_em     timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_evt_tenant_id UNIQUE (tenant_id, id)
);
CREATE INDEX IF NOT EXISTS ix_evt_proc ON evento_webhook (tenant_id, processado);

-- ----------------------------------------------------------------------------
-- atendente_depto / atendente_numero — vínculos N:N de fila e de canal.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS atendente_depto (
  tenant_id       bigint NOT NULL DEFAULT tenant_atual() REFERENCES tenant (id),
  atendente_id    bigint NOT NULL,
  departamento_id bigint NOT NULL,
  criado_em       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT pk_atddep     PRIMARY KEY (tenant_id, atendente_id, departamento_id),
  CONSTRAINT fk_atddep_atd FOREIGN KEY (tenant_id, atendente_id)    REFERENCES atendente (tenant_id, id),
  CONSTRAINT fk_atddep_dep FOREIGN KEY (tenant_id, departamento_id) REFERENCES departamento (tenant_id, id)
);
CREATE INDEX IF NOT EXISTS ix_atddep_dep ON atendente_depto (tenant_id, departamento_id);

CREATE TABLE IF NOT EXISTS atendente_numero (
  tenant_id    bigint NOT NULL DEFAULT tenant_atual() REFERENCES tenant (id),
  atendente_id bigint NOT NULL,
  numero_id    bigint NOT NULL,
  CONSTRAINT pk_atd_num  PRIMARY KEY (tenant_id, atendente_id, numero_id),
  CONSTRAINT fk_an_atd   FOREIGN KEY (tenant_id, atendente_id) REFERENCES atendente (tenant_id, id),
  CONSTRAINT fk_an_num   FOREIGN KEY (tenant_id, numero_id)    REFERENCES numero (tenant_id, id)
);
CREATE INDEX IF NOT EXISTS ix_an_num ON atendente_numero (tenant_id, numero_id);

-- ----------------------------------------------------------------------------
-- config — chave/valor por tenant, editável pelo ADMIN no painel.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS config (
  tenant_id     bigint NOT NULL DEFAULT tenant_atual() REFERENCES tenant (id),
  chave         varchar(60) NOT NULL,
  valor         text,
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT pk_config PRIMARY KEY (tenant_id, chave)
);

-- ----------------------------------------------------------------------------
-- ia_config / ia_turno / ia_autorizado — bot de IA.
-- ia_config: 1 linha por tenant (id fixo = 1), chave cifrada AES-256-GCM.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ia_config (
  tenant_id             bigint NOT NULL DEFAULT tenant_atual() REFERENCES tenant (id),
  id                    bigint NOT NULL DEFAULT 1,
  provider              varchar(30)  NOT NULL,
  modelo                varchar(100) NOT NULL,
  base_url              varchar(500),
  api_key_criptografada varchar(2000) NOT NULL,
  ativo                 char(1) NOT NULL DEFAULT 'S',
  atualizado_por        bigint,
  atualizado_em         timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT pk_iaconf       PRIMARY KEY (tenant_id, id),
  CONSTRAINT ck_iaconf_prov  CHECK (provider IN ('anthropic','openai','openrouter','ollama','vllm','groq')),
  CONSTRAINT ck_iaconf_ativo CHECK (ativo IN ('S','N')),
  CONSTRAINT fk_iaconf_atd   FOREIGN KEY (tenant_id, atualizado_por) REFERENCES atendente (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS ia_turno (
  id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  tenant_id    bigint NOT NULL DEFAULT tenant_atual() REFERENCES tenant (id),
  conversa_id  bigint NOT NULL,
  numero_turno integer,
  papel        varchar(20),
  conteudo     text,
  tool_json    jsonb,
  ts           timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_turno_tenant_id UNIQUE (tenant_id, id),
  CONSTRAINT fk_turno_conv      FOREIGN KEY (tenant_id, conversa_id) REFERENCES conversa (tenant_id, id)
);
CREATE INDEX IF NOT EXISTS ix_turno_conv ON ia_turno (tenant_id, conversa_id, numero_turno);

CREATE TABLE IF NOT EXISTS ia_autorizado (
  id        bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL DEFAULT tenant_atual() REFERENCES tenant (id),
  telefone  varchar(20) NOT NULL,
  nome      varchar(200),
  numero_id bigint NOT NULL,
  ativo     char(1) NOT NULL DEFAULT 'S',
  criado_em timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_iaaut_tenant_id UNIQUE (tenant_id, id),
  CONSTRAINT uq_iaaut           UNIQUE (tenant_id, telefone, numero_id),
  CONSTRAINT ck_iaaut_ativo     CHECK (ativo IN ('S','N')),
  CONSTRAINT fk_iaaut_num       FOREIGN KEY (tenant_id, numero_id) REFERENCES numero (tenant_id, id)
);
CREATE INDEX IF NOT EXISTS ix_iaaut_tel ON ia_autorizado (tenant_id, telefone, ativo);

-- ============================================================================
-- ROW-LEVEL SECURITY — ENABLE + FORCE + policy `isolamento_tenant` por tabela.
-- Sem contexto (tenant_atual() IS NULL) nenhuma linha é visível nem gravável.
-- ============================================================================
DO $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'departamento','atendente','numero','template','contato','tag','fluxo',
    'conversa','mensagem','resposta_rapida','campanha','campanha_item',
    'auditoria','evento_webhook','atendente_depto','atendente_numero',
    'config','ia_config','ia_turno','ia_autorizado'
  ] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format('DROP POLICY IF EXISTS isolamento_tenant ON %I', t);
    EXECUTE format(
      'CREATE POLICY isolamento_tenant ON %I '
      || 'USING (tenant_id = tenant_atual()) '
      || 'WITH CHECK (tenant_id = tenant_atual())', t);
  END LOOP;
END
$$;

-- tenant: o tenant enxerga a própria linha; contexto NULO (operador/
-- provisionamento) enxerga e administra tudo — APENAS nesta tabela.
ALTER TABLE tenant ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenant FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_proprio  ON tenant;
DROP POLICY IF EXISTS tenant_operador ON tenant;
CREATE POLICY tenant_proprio  ON tenant
  USING (id = tenant_atual());
CREATE POLICY tenant_operador ON tenant
  USING (tenant_atual() IS NULL)
  WITH CHECK (tenant_atual() IS NULL);

-- ============================================================================
-- ROLE DE APLICAÇÃO — sem BYPASSRLS (ver ⚠️ no cabeçalho).
--
-- NOLOGIN de propósito: ninguém conecta como `falatta_app`. O app conecta com
-- o usuário do DATABASE_URL e assume este papel por transação, via
-- `SET LOCAL ROLE falatta_app` (feito por comTenant() em db/pool.js).
-- Sem isso, um usuário-dono com rolbypassrls atravessa todas as policies.
-- ============================================================================
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'falatta_app') THEN
    CREATE ROLE falatta_app NOLOGIN NOBYPASSRLS;
  END IF;
END
$$;

-- Permite ao usuário de conexão assumir o papel (SET ROLE exige ser membro).
GRANT falatta_app TO CURRENT_USER;

GRANT USAGE ON SCHEMA public TO falatta_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO falatta_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO falatta_app;
-- Tabelas/sequências criadas por migrações futuras já nascem acessíveis.
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO falatta_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO falatta_app;
