-- ============================================================================
-- MC-ZAP — FASE 5A: Departamentos, vínculo Atendente x Departamento e ajustes
-- Rodar como MCLABS (mesmo usuário do install original).
-- (Script portável: sem comandos SQL*Plus — roda em SQL*Plus, SQLcl,
--  SQL Developer e na Command Window do PL/SQL Developer.)
-- IDEMPOTENCIA: NAO eh idempotente (rodar 2x gera erro). REQUER Oracle 12c+.
-- ============================================================================

-- 1) Departamentos/equipes (Apoio a Vendas, Financeiro-Crédito, Cobrança, T.I...).
CREATE TABLE MC_ZAP_DEPARTAMENTO (
  ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  NOME       VARCHAR2(80) NOT NULL,
  DESCRICAO  VARCHAR2(200),
  COR        VARCHAR2(9),
  ATIVO      CHAR(1) DEFAULT 'S' NOT NULL,
  CRIADO_EM  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT UQ_MCZAP_DEPTO_NOME UNIQUE (NOME),
  CONSTRAINT CK_MCZAP_DEPTO_ATIVO CHECK (ATIVO IN ('S','N'))
);

-- 2) Vínculo N:N atendente x departamento (atendente pode atender várias filas).
CREATE TABLE MC_ZAP_ATENDENTE_DEPTO (
  ATENDENTE_ID     NUMBER NOT NULL,
  DEPARTAMENTO_ID  NUMBER NOT NULL,
  CRIADO_EM        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_MCZAP_ATDDEP PRIMARY KEY (ATENDENTE_ID, DEPARTAMENTO_ID),
  CONSTRAINT FK_MCZAP_ATDDEP_ATD FOREIGN KEY (ATENDENTE_ID)
    REFERENCES MC_ZAP_ATENDENTE (ID),
  CONSTRAINT FK_MCZAP_ATDDEP_DEP FOREIGN KEY (DEPARTAMENTO_ID)
    REFERENCES MC_ZAP_DEPARTAMENTO (ID)
);
CREATE INDEX IX_MCZAP_ATDDEP_DEP ON MC_ZAP_ATENDENTE_DEPTO (DEPARTAMENTO_ID);

-- 3) Número ganha departamento padrão (roteamento de inbound quando não há bot).
ALTER TABLE MC_ZAP_NUMERO ADD (
  DEPARTAMENTO_PADRAO_ID NUMBER,
  CONSTRAINT FK_MCZAP_NUM_DEPPAD FOREIGN KEY (DEPARTAMENTO_PADRAO_ID)
    REFERENCES MC_ZAP_DEPARTAMENTO (ID)
);

-- 4) Atendente ganha presença persistida (pausa sobrevive a restart do serviço).
ALTER TABLE MC_ZAP_ATENDENTE ADD (
  STATUS_PRESENCA VARCHAR2(10) DEFAULT 'offline' NOT NULL,
  CONSTRAINT CK_MCZAP_ATD_PRES CHECK (STATUS_PRESENCA IN ('online','pausa','offline'))
);

-- 5) Seed dos departamentos (espelha a estrutura usada hoje no EZChat).
INSERT INTO MC_ZAP_DEPARTAMENTO (NOME, DESCRICAO, COR) VALUES ('Apoio a Vendas',        'Suporte ao time comercial',           '#1B5E7B');
INSERT INTO MC_ZAP_DEPARTAMENTO (NOME, DESCRICAO, COR) VALUES ('Financeiro - Crédito',  'Análise e liberação de crédito',      '#2F7D4F');
INSERT INTO MC_ZAP_DEPARTAMENTO (NOME, DESCRICAO, COR) VALUES ('Financeiro - Cobrança', 'Cobrança de títulos vencidos',        '#9B1B1B');
INSERT INTO MC_ZAP_DEPARTAMENTO (NOME, DESCRICAO, COR) VALUES ('T.I',                   'Suporte de tecnologia',               '#5B4B8A');
INSERT INTO MC_ZAP_DEPARTAMENTO (NOME, DESCRICAO, COR) VALUES ('Transporte',            'Logística e entregas',                '#B7791F');
COMMIT;

-- 6) Verificação: deve listar 2 tabelas novas VALID + 5 departamentos.
SELECT object_name, status FROM user_objects
 WHERE object_name IN ('MC_ZAP_DEPARTAMENTO','MC_ZAP_ATENDENTE_DEPTO')
 ORDER BY object_name;
SELECT ID, NOME, COR FROM MC_ZAP_DEPARTAMENTO ORDER BY ID;
