-- ============================================================================
-- MC-ZAP — FASE 5C: Chatbot com fluxos (autoatendimento por menus).
-- Rodar como MCLABS, DEPOIS do 03_fase5b.sql.
-- (Script portável: sem comandos SQL*Plus.)
-- IDEMPOTENCIA: NAO eh idempotente (rodar 2x gera erro). REQUER Oracle 12c+.
-- ============================================================================

-- 1) Definição dos fluxos (JSON com nós: mensagem/menu/pergunta/transferir/encerrar).
--    Um fluxo ATIVO por número: conversas novas desse número entram no bot.
CREATE TABLE MC_ZAP_FLUXO (
  ID            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  NOME          VARCHAR2(120) NOT NULL,
  NUMERO_ID     NUMBER,
  DEFINICAO     CLOB NOT NULL,
  ATIVO         CHAR(1) DEFAULT 'N' NOT NULL,
  VERSAO        NUMBER DEFAULT 1 NOT NULL,
  CRIADO_POR    NUMBER,
  CRIADO_EM     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  ATUALIZADO_EM TIMESTAMP,
  CONSTRAINT FK_MCZAP_FLUXO_NUM FOREIGN KEY (NUMERO_ID) REFERENCES MC_ZAP_NUMERO (ID),
  CONSTRAINT FK_MCZAP_FLUXO_ATD FOREIGN KEY (CRIADO_POR) REFERENCES MC_ZAP_ATENDENTE (ID),
  CONSTRAINT CK_MCZAP_FLUXO_ATIVO CHECK (ATIVO IN ('S','N')),
  CONSTRAINT CK_MCZAP_FLUXO_DEF CHECK (DEFINICAO IS JSON)
);
CREATE INDEX IX_MCZAP_FLUXO_NUM ON MC_ZAP_FLUXO (NUMERO_ID, ATIVO);

-- 2) Estado do bot por conversa (1:1, vida curta — limpo ao transferir/encerrar).
ALTER TABLE MC_ZAP_CONVERSA ADD (
  BOT_FLUXO_ID         NUMBER,
  BOT_NO_ATUAL         VARCHAR2(40),
  BOT_VARIAVEIS        VARCHAR2(2000),
  BOT_INVALIDAS        NUMBER DEFAULT 0,
  BOT_ULTIMA_INTERACAO TIMESTAMP,
  CONSTRAINT FK_MCZAP_CONV_FLUXO FOREIGN KEY (BOT_FLUXO_ID) REFERENCES MC_ZAP_FLUXO (ID),
  CONSTRAINT CK_MCZAP_CONV_BOTVAR CHECK (BOT_VARIAVEIS IS NULL OR BOT_VARIAVEIS IS JSON)
);

-- 3) Verificação.
SELECT object_name, status FROM user_objects
 WHERE object_name = 'MC_ZAP_FLUXO';
SELECT COLUMN_NAME FROM USER_TAB_COLUMNS
 WHERE TABLE_NAME = 'MC_ZAP_CONVERSA' AND COLUMN_NAME LIKE 'BOT%'
 ORDER BY COLUMN_NAME;
