-- ============================================================================
-- MC-ZAP — Bot de IA (MulticanalOS pelo WhatsApp).
-- Rodar como MCLABS, APÓS 15_horario_atendimento.sql.
-- (Script portável: sem comandos SQL*Plus.)
-- A coluna MODO é não-idempotente (ALTER 2x dá erro); as tabelas IA são
-- recriaveis (DROP + CREATE, sem MERGE); INSERT de autorização é re-rodável.
--
-- Objetivo: automatizar atendimento via modelo de IA (Anthropic, OpenAI, etc.),
-- com controle por número e autorização por telefone específico.
-- ============================================================================
SET DEFINE OFF;

-- 1) Modo do número: 'padrao' = fluxo determinístico; 'ia' = bot de IA.
ALTER TABLE MC_ZAP_NUMERO ADD (MODO VARCHAR2(10) DEFAULT 'padrao' NOT NULL
  CONSTRAINT CK_MCZAP_NUM_MODO CHECK (MODO IN ('padrao','ia')));

-- 1b) Libera FILA_STATUS='ia' no CHECK da conversa (criado no 03_fase5b só com
-- 'bot','aguardando','em_atendimento','resolvida'). Sem isto o webhook falha
-- com ORA-02290 ao criar a conversa da IA. Idempotente.
BEGIN
  BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE MC_ZAP_CONVERSA DROP CONSTRAINT CK_MCZAP_CONV_FILA';
  EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -2443 THEN RAISE; END IF;  -- ORA-02443 = constraint não existe (ok)
  END;
  EXECUTE IMMEDIATE
    'ALTER TABLE MC_ZAP_CONVERSA ADD CONSTRAINT CK_MCZAP_CONV_FILA ' ||
    'CHECK (FILA_STATUS IN (''bot'',''aguardando'',''em_atendimento'',''resolvida'',''ia''))';
END;
/

-- 2) Provedor de IA ativo (1 linha, ID fixo = 1). API key criptografada (AES-256-GCM).
CREATE TABLE MC_ZAP_IA_CONFIG (
  ID                    NUMBER DEFAULT 1 PRIMARY KEY,
  PROVIDER              VARCHAR2(30)  NOT NULL,
  MODELO                VARCHAR2(100) NOT NULL,
  BASE_URL              VARCHAR2(500),
  API_KEY_CRIPTOGRAFADA VARCHAR2(2000) NOT NULL,
  ATIVO                 CHAR(1) DEFAULT 'S' NOT NULL,
  ATUALIZADO_POR        NUMBER,
  ATUALIZADO_EM         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT CK_MCZAP_IACONF_PROV  CHECK (PROVIDER IN ('anthropic','openai','openrouter','ollama','vllm','groq')),
  CONSTRAINT CK_MCZAP_IACONF_ATIVO CHECK (ATIVO IN ('S','N')),
  CONSTRAINT FK_MCZAP_IACONF_ATD FOREIGN KEY (ATUALIZADO_POR) REFERENCES MC_ZAP_ATENDENTE (ID)
);

-- 3) Histórico estruturado da conversa com o modelo (contexto multi-turno).
CREATE TABLE MC_ZAP_IA_TURNO (
  ID           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  CONVERSA_ID  NUMBER NOT NULL,
  NUMERO_TURNO NUMBER,
  PAPEL        VARCHAR2(20),  -- 'user' | 'assistant' | 'tool'
  CONTEUDO     CLOB,
  TOOL_JSON    CLOB,
  TS           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_MCZAP_TURNO_CONV FOREIGN KEY (CONVERSA_ID) REFERENCES MC_ZAP_CONVERSA (ID)
);
CREATE INDEX IX_MCZAP_TURNO_CONV ON MC_ZAP_IA_TURNO (CONVERSA_ID, NUMERO_TURNO);

-- 4) Telefones autorizados a falar com o bot (gate). Sem linhas p/ um número = ninguém entra.
CREATE TABLE MC_ZAP_IA_AUTORIZADO (
  ID        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  TELEFONE  VARCHAR2(20) NOT NULL,
  NOME      VARCHAR2(200),
  NUMERO_ID NUMBER NOT NULL,
  ATIVO     CHAR(1) DEFAULT 'S' NOT NULL,
  CRIADO_EM TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT UQ_MCZAP_IAAUT UNIQUE (TELEFONE, NUMERO_ID),
  CONSTRAINT FK_MCZAP_IAAUT_NUM FOREIGN KEY (NUMERO_ID) REFERENCES MC_ZAP_NUMERO (ID),
  CONSTRAINT CK_MCZAP_IAAUT_ATIVO CHECK (ATIVO IN ('S','N'))
);
CREATE INDEX IX_MCZAP_IAAUT_TEL ON MC_ZAP_IA_AUTORIZADO (TELEFONE, ATIVO);

COMMIT;

-- 5) Verificação pós-aplicação.
SELECT COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'MC_ZAP_NUMERO' AND COLUMN_NAME = 'MODO';
SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME IN ('MC_ZAP_IA_CONFIG','MC_ZAP_IA_TURNO','MC_ZAP_IA_AUTORIZADO');
